---
dependencies: []

galaxy_info:
  role_name: jenkins
  author: geerlingguy
  description: Jenkins CI
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.10
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - packaging
    - jenkins
    - ci
