---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Common roles for preparing the image
- name: Check inputs, prepare logs, hostname, install basic dependencies and AWS Data Provider
  become: yes
  hosts: all
  roles:
    - role: check-inputs
      vars:
        input_variables_to_check: 
          - EC2_HOSTNAME
          - PRIVATE_DNS_ZONE
          - MASTER_PASSWORD
          - EFS_ID
          - HANA_PRIVATE_IP
          - HANA_HOSTNAME
          - S3_BUCKET_MEDIA_FILES
    - role: common-os-tasks
    - role: prepare-logs-folders
    - role: set-hostname
      vars:
        extra_vars_to_add_to_hosts:
          - private_ip: "{{ GLOBAL_PAS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_PAS_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_HANA_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_HANA_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_ERS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_ERS_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_ASCS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_ASCS_HOSTNAME }}"
    - role: install-pkg-mgr-dependencies
    - role: install-aws-sap-data-provider

# Installation-specific roles
- name: Mount disks and set parameters
  become: yes
  hosts: all
  roles:
    - role: ansible-role-disks

# # RedHat official roles for preparing for SAP Installation
# - name: Prepare host with RedHat certified roles
#   become: yes
#   hosts: all
#   roles:
#     - role: sap_general_preconfigure
#       vars:
#         sap_general_preconfigure_selinux_state: disabled
#         sap_general_preconfigure_fail_if_reboot_required: false
#     - role: sap_netweaver_preconfigure

# Download and install
- name: Download and Install
  become: yes
  hosts: all
  roles:
    - role: ansible-role-download-and-install

- name: Enable HA
  become: yes
  hosts: all
  roles:
    - role: ansible-role-enable-ha